baseurl = "https://fitter-thought-74575.netlify.app/"
theme = "theme"
title = "Marcela Monnerat Estética Avançada"

[author]
  name = "Marcela Monnerat"
  instagram = "marcela.monnerat"
  facebook = ""
